spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

keystone:
  jwt:
    secret: ${JWT_SECRET:ljnkNJ6pd7rbOJ9K9EgLU3+ZIXlxpnzA9kn+6vWbkE4=}
    expiration-ms: 86400000
  scheduler:
    sla-check-cron: "0 */15 * * * *"

server:
  port: ${PORT:8080}