spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false

keystone:
  jwt:
    secret: ${JWT_SECRET:ljnkNJ6pd7rbOJ9K9EgLU3+ZIXlxpnzA9kn+6vWbkE4=}
    expiration-ms: 86400000
  scheduler:
    sla-check-cron: "0 */15 * * * *"
